// <auto-generated />
using MOTTHRU.API.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MOTTHRU.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251102024518_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.MotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_moto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("chassi");

                    b.Property<string>("NumMotor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("num_motor");

                    b.Property<int>("PatioId")
                        .HasColumnType("integer")
                        .HasColumnName("patio_id_patio");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("placa");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("moto");
                });

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.PatioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_patio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomePatio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome_patio");

                    b.HasKey("Id");

                    b.ToTable("patio");
                });

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.RfidEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rfid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MotoId")
                        .HasColumnType("integer")
                        .HasColumnName("moto_id_moto");

                    b.Property<string>("Sinal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sinal");

                    b.HasKey("Id");

                    b.HasIndex("MotoId");

                    b.ToTable("rfid");
                });

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.MotoEntity", b =>
                {
                    b.HasOne("MOTTHRU.API.Domain.Entities.PatioEntity", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.RfidEntity", b =>
                {
                    b.HasOne("MOTTHRU.API.Domain.Entities.MotoEntity", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("MOTTHRU.API.Domain.Entities.PatioEntity", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
